language: c
compiler:
  - clang
  - gcc
env:
  - NGINX=1.9.11
  - NGINX=1.8.1
sudo: false
cache: ccache
addons:
  apt:
    packages:
    - libpcre3-dev
    - libssl-dev
    - perl
before_install:
  - perlbrew install perl-5.18.2
  - perlbrew switch perl-5.18.2
  - perl -v
  - env PERL_MM_USE_DEFAULT=1 cpan -fi Test::Nginx::Socket
install:
  - wget -O - http://nginx.org/download/nginx-${NGINX}.tar.gz | tar -xzf -
  - cd nginx-${NGINX}
  - git clone https://github.com/openresty/headers-more-nginx-module.git -b v0.29
  - ./configure --with-debug --add-module=.. --add-module=./headers-more-nginx-module
  - make
  - export PATH=$(pwd)/objs:$PATH
  - cd ..
script: |
  PERL5LIB=$HOME/perl5/lib/perl5 prove -v
