language: c
compilers:
  - clang
  - gcc
env:
  # Don't use `NGINX` as the variable name or Nginx won't daemonise
  - SHIB_NGINX_VERSION=1.9.13
  - SHIB_NGINX_VERSION=1.8.1
sudo: false
addons:
  apt:
    packages:
      - libpcre3-dev
      - libssl-dev
      - perl
      - cpanminus
cache:
  apt: true
  cpan: true
  ccache: true
  directories:
    - $HOME/perl5
before_install:
  - cpanm --notest --local-lib=$HOME/perl5 Test::Nginx
install:
  - wget -O - http://nginx.org/download/nginx-${SHIB_NGINX_VERSION}.tar.gz | tar -xzf -
  - cd nginx-${SHIB_NGINX_VERSION}
  - git clone https://github.com/openresty/headers-more-nginx-module.git -b v0.29
  - ./configure --with-debug --add-module=.. --add-module=./headers-more-nginx-module
  - make
  - export PATH=$(pwd)/objs:$PATH
  - cd ..
script:
  - PERL5LIB=$HOME/perl5/lib/perl5 TEST_NGINX_VERBOSE=true prove -v
after_failure:
  - cat t/servroot/conf/nginx.conf
  - cat t/servroot/access.log
  - cat t/servroot/error.log
